version: '3'

services:

    shlink_db_postgres:
        container_name: shlink_db_postgres
        restart: always
        image: postgres:12.2-alpine
        ports:
            - "5433:5432"
        volumes:
            - ./:/home/shlink/www
            - ./data/infra/database_pg:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: shlink
            PGDATA: /var/lib/postgresql/data/pgdata
            
    shlink:
        container_name: my_shlink
        image: ghcr.io/shlinkio/shlink:stable-roadrunner
        restart: always
        depends_on:
            - shlink_db_postgres
        ports:
            - "7878:8080"
        links:
            - shlink_db_postgres
        environment:
            DB_DRIVER: postgres
            DB_USER: postgres
            DB_PASSWORD: root
            DB_PORT: 5432
            DB_HOST: shlink_db_postgres
            GEOLITE_LICENSE_KEY: RBv1HoSfqVkIxHHf
            IS_HTTPS_ENABLED: true
            DEFAULT_DOMAIN: brid.gq
            DEFAULT_SHORT_CODES_LENGTH: 4
            TIMEZONE: Asia/Taipei
            REDIRECT_STATUS_CODE: 301
            REDIRECT_CACHE_LIFETIME: 300
            ANONYMIZE_REMOTE_ADDR: false
            
