# wrangler.toml
name = "url-shortener"
main = "worker.js"
compatibility_date = "2023-01-01"

[site]
bucket = "./public"

[[routes]]
pattern = "404.brid.pw/invalid-short-code*"
zone_id = "<your-zone-id>